# Generated by Django 4.1 on 2022-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
