# Generated by Django 4.1 on 2022-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_direccion_empleado_sucursal_tipocliente_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
