# Generated by Django 4.1 on 2022-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20)),
                ('card_cvv', models.CharField(max_length=4)),
                ('card_valid_date', models.IntegerField(max_length=7)),
                ('card_expire_date', models.IntegerField(max_length=7)),
                ('card_type', models.CharField(max_length=7)),
            ],
        ),
    ]
