# Generated by Django 4.1 on 2022-08-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('brand_card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_card_name', models.TextField()),
            ],
            options={
                'db_table': 'Marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
    ]
