# Generated by Django 4.1 on 2022-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0002_marcatarjeta_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarjeta',
            table='Tarjeta',
        ),
    ]
