# Generated by Django 4.1 on 2022-08-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_surname', models.CharField(max_length=255)),
                ('customer_dni', models.CharField(max_length=9)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
