# Generated by Django 4.1 on 2022-08-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_surname', models.CharField(max_length=255)),
                ('employee_hire_date', models.CharField(max_length=10)),
                ('employee_dni', models.CharField(max_length=9)),
            ],
        ),
    ]
