# Generated by Django 4.1 on 2022-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=True)),
                ('iban', models.CharField(max_length=31)),
            ],
        ),
    ]
