# Generated by Django 4.1 on 2022-08-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_date', models.CharField(max_length=11)),
                ('transaction_total', models.IntegerField()),
                ('account_id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.model', verbose_name=''))),
            ],
        ),
    ]
