# Generated by Django 4.1 on 2022-08-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={'managed': False},
        ),
    ]
