# Generated by Django 4.1 on 2022-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_date',
            field=models.DateTimeField(),
        ),
    ]
