# Generated by Django 4.1 on 2022-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamos',
            table='prestamo',
        ),
    ]
