# Generated by Django 4.1 on 2022-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_tipocuenta_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuenta',
            table='cuenta',
        ),
    ]
