# Generated by Django 4.0.6 on 2022-08-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProceso', '0002_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='branch_number',
        ),
    ]
