# Generated by Django 4.0.6 on 2022-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProceso', '0004_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
