# Generated by Django 4.0.6 on 2022-08-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProceso', '0005_alter_prestamo_loan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField()),
                ('card_cvv', models.TextField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
