# Generated by Django 4.1 on 2022-08-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProceso', '0006_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='saldo',
            new_name='balance',
        ),
    ]
