# Generated by Django 4.1 on 2022-08-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=11)),
                ('loan_date', models.CharField(max_length=10)),
                ('loan_total', models.IntegerField()),
            ],
        ),
    ]
